# Generated by Django 3.1.7 on 2021-03-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventId', models.AutoField(primary_key=True, serialize=False)),
                ('EventAddress', models.CharField(max_length=100)),
                ('AvailableTickets', models.PositiveIntegerField()),
                ('TotalTickets', models.PositiveIntegerField()),
                ('EventDate', models.DateTimeField()),
                ('EventWebsite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('MovieId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieName', models.CharField(max_length=100)),
                ('MovieDuration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserEmail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UserPassword', models.CharField(max_length=256)),
                ('UserName', models.CharField(max_length=100)),
                ('UserPhoneNumber', models.CharField(max_length=20)),
                ('IsBusiness', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('WatchlistId', models.AutoField(primary_key=True, serialize=False)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationId', models.AutoField(primary_key=True, serialize=False)),
                ('TicketsReserved', models.PositiveIntegerField()),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.event')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('CardNumber', models.CharField(max_length=256)),
                ('ExpDate', models.CharField(max_length=256)),
                ('SecCode', models.CharField(max_length=256)),
                ('Address', models.CharField(max_length=100)),
                ('ZipCode', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='MovieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='event',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user'),
        ),
    ]
