# Generated by Django 3.2 on 2021-05-05 03:14

from django.db import migrations, models
import django.utils.timezone
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210415_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, validators=[movies.validators.validate_name_length, movies.validators.validate_username_alphadigits]),
            preserve_default=False,
        ),
    ]
