# Generated by Django 3.1.7 on 2021-04-13 20:46

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210413_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='UserEmail',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, validators=[movies.validators.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserName',
            field=models.CharField(max_length=100, validators=[movies.validators.validate_name_length, movies.validators.validate_username_alphadigits]),
        ),
    ]
