# Generated by Django 3.2 on 2021-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_event_locationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventName',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
