# Generated by Django 3.2 on 2021-05-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210415_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
