# Generated by Django 3.2 on 2021-05-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_watchlist_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='Favorites',
        ),
    ]
