# Generated by Django 3.1.7 on 2021-03-31 01:00

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210330_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserEmail',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, validators=[movies.validators.validate_name_length]),
        ),
    ]
