# Generated by Django 3.1.7 on 2021-04-01 03:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20210331_0100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('auth_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
