# Generated by Django 3.1.7 on 2021-04-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210401_0548'),
        ('movies', '0007_auto_20210401_0405'),
    ]

    operations = [
    ]
