# Generated by Django 3.2 on 2021-04-14 17:12

from django.db import migrations, models
import movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_merge_20210401_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='owner',
            new_name='Owner',
        ),
        migrations.AlterField(
            model_name='event',
            name='EventWebsite',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovieDuration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='CardNumber',
            field=models.CharField(max_length=256, validators=[movies.validators.validate_card_number]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ExpDate',
            field=models.CharField(max_length=256, validators=[movies.validators.validate_expiration_date]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='SecCode',
            field=models.CharField(max_length=256, validators=[movies.validators.validate_security_code]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ZipCode',
            field=models.CharField(max_length=10, validators=[movies.validators.validate_zip_code]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='TicketsReserved',
            field=models.IntegerField(validators=[movies.validators.validate_tickets_reserved]),
        ),
    ]
